# Site Settings
site_name: Engenharia de Dados
site_author: Maciel Vidal
docs_dir: content

repo_name: insper/dataeng
repo_url: https://github.com/insper/dataeng
copyright: © 2025 | @macielcalebe

nav:
  - Início: index.md
  - Aulas:
      - 01 - Introdução:
          - classes/01-intro/intro.md
          - classes/01-intro/profissionais.md
          - classes/01-intro/warmup.md
          - classes/01-intro/processar.md
      - 02 - Filas e Containers:
          - classes/02-docker-filas/relembrar-ciclo.md
          - classes/02-docker-filas/filas.md
          - classes/02-docker-filas/docker.md
          - classes/02-docker-filas/rabbitmq.md
          - classes/02-docker-filas/programar-sensores.md
          - classes/02-docker-filas/programar-pipeline.md
      - 03 - Data Warehousing:
          - Parte I:
              - classes/03-data-warehouse/intro.md
              - classes/03-data-warehouse/linha-tempo.md
              - classes/03-data-warehouse/data-warehousing.md
              - classes/03-data-warehouse/pratica.md
          - Parte II:
              - classes/03-data-warehouse/olap.md
              - classes/03-data-warehouse/uv.md
              - classes/03-data-warehouse/duckdb.md
              - classes/03-data-warehouse/clickhouse.md
              - classes/03-data-warehouse/links.md
      - 04 - Computação em Nuvem:
          - classes/04-cloud/intro.md
          - classes/04-cloud/config-aws-cli.md
          - classes/04-cloud/pratica.md
      - 05 - Infrastructure as Code:
          - classes/05-iac/intro.md
          - classes/05-iac/pratica.md
      - 06 - Intro Orquestração:
          - classes/06-intro-orchestration/intro-cron.md
          - classes/06-intro-orchestration/intro-orchestration.md
          - classes/06-intro-orchestration/prefect.md
          - classes/06-intro-orchestration/references.md
      - 07 - Modelagem de Dados:
          - classes/07-data-modeling/intro-data-modeling.md
          - classes/07-data-modeling/obt.md
          - classes/07-data-modeling/star-schema.md
          - classes/07-data-modeling/snowflake.md
          - classes/07-data-modeling/references.md
      - 08 - Entrevista 01:
          - classes/08-interview-01/faq.md
          - classes/08-interview-01/int01.md
      - 09 - Data Lakes:
          - classes/09-data-lakes/intro-data-lakes.md
          - classes/09-data-lakes/aws-glue.md
      - 10 - Data Lakehouse:
          - classes/10-data-lakehouse/intro-data-lakehouse.md
          - classes/10-data-lakehouse/minio.md
          - classes/10-data-lakehouse/iceberg.md
          - classes/10-data-lakehouse/trino.md
          - classes/10-data-lakehouse/references.md
      - 11 - Observabilidade:
          - classes/11-observability/intro-observability.md
          - classes/11-observability/prometheus.md
          - classes/11-observability/grafana.md
          - classes/11-observability/logging.md
          - classes/11-observability/tracing.md
          - classes/11-observability/references.md
      - 12 - Orquestração:
          - Parte I:
              - classes/12-orchestration-airflow/intro-airflow.md
              - classes/12-orchestration-airflow/pratica-airflow.md
          - Parte II:
              - classes/12-orchestration-airflow/airflow-emr.md
      - 13 - Databricks:
          - Parte I:
              - classes/13-databricks/intro-paas.md
              - classes/13-databricks/intro-databricks.md
              - classes/13-databricks/databricks-pratica.md
          - Parte II:
              - classes/13-databricks/databricks-aws-setup.md
              - classes/13-databricks/databricks-etl.md
      - 14 - Entrevista 02:
          - classes/14-interview02/int02.md
      - 15 - SGBDR - Performance:
          - Parte I:
              - classes/15-query-opt/intro.md
              - classes/15-query-opt/config-db.md
              - classes/15-query-opt/tpcb.md
              - classes/15-query-opt/intro-indexes.md
              - classes/15-query-opt/pratica-indexes.md
          - Parte II:
              - classes/15-query-opt/indexes-views-subqueries.md
              - classes/15-query-opt/pg-read-replica.md
          - Parte III:
              - classes/15-query-opt/api.md
      - 16 - System Design:
          - classes/16-system-design/intro-system-design.md
          - classes/16-system-design/framework.md
          - classes/16-system-design/references.md
      - 17 - Entrevista 03:
          - classes/17-interview03/pre-interview1.md
          - classes/17-interview03/pre-interview2.md
          - classes/17-interview03/int03.md
          - classes/17-interview03/references.md
  - Entrevistas:
      - 08 - Entrevista 01:
          - classes/08-interview-01/faq.md
          - classes/08-interview-01/int01.md
      - 14 - Entrevista 02:
          - classes/14-interview02/int02.md
      - 17 - Entrevista 03:
          - classes/17-interview03/pre-interview1.md
          - classes/17-interview03/pre-interview2.md
          - classes/17-interview03/int03.md
          - classes/17-interview03/references.md
  - APS:
      - aps/aps01/aps01.md
  - Projeto: project/project.md
  - Regras: about.md
  - Deadlines: deadlines.md
  - Contribuições: contributions.md

extra:
  home_cover_image: attachments/home-image.png
  home_tagline: Engenharia de Dados
  home_description: |
    Seja bem-vindo ao curso eletivo de Engenharia de Dados do Insper! Navegue pelos links do menu para acessar os conteúdos.

  home_gradient_hsla: hsla(160deg,47%,55%,1)

  home_button1_name: Aulas
  home_button1_url: classes/01-intro/intro/
  home_button1_theme: md-button  md-button--primary
  home_button1_icon: book
  home_button1_blurb: |
    Material das aulas, que serão apresentadas no formato de handout.

  home_button2_name: Regras # Comment this parameter out to remove the button.
  home_button2_url: about # This path starts at your root mkdocs directory.
  home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
  home_button2_icon: rule # Options: "people", "gear", "image", "calendar", "rule","book"
  home_button2_blurb: | # Short description of this button / section.
    Conheça detalhes sobre o curso, como as atividades, as regras e o que é esperado de você.

  home_button3_name: Deadlines
  home_button3_url: deadlines
  home_button3_theme: md-button
  home_button3_icon: calendar
  home_button3_blurb: |
    Confira os deadlines do curso, com as datas de entrega das atividades.

# # Homepage Code Execution
# home_execute_js: | # Javascript to execute when accessing the homepage
#   console.log("This is an example!");

extra_javascript:
  - js/tabs.js
  - js/termynal.js
  - js/custom.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
extra_css:
  - css/termynal.css

theme:
  name: material
  custom_dir: assets

  features:
    - navigation.indexes # Implied section 'index.md' files
    - navigation.tabs # Static upper section tabs (exist)
    - navigation.tabs.sticky # Static upper section tabs (stay)
    - navigation.footer # Add 'previous' and 'next' buttons in the footer
    - navigation.instant # Keep navigation from reloading
    - navigation.instant.progress # Display page loading progress-bar ( > 400ms)
    - search.highlight # Highlight all occurrences of queried string
    - search.share # Search Query can be copied to Clipboard
    - search.suggest # Display likeliest completion for the last queried word

  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey #deep purple # deep orange
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode

    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: dark blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - footnotes
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: content
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - abbr
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - roamlinks # Obsidian Style Image Support ![[<attachment_name>]]
  - mkdocs_quiz
